#!/bin/bash
python3 -m $(basename $PYFILE .py)
mv ./__pycache__/*$(basename $PYFILE .py)* $(basename $PYFILE .py).pyc
cp ./__pycache__/$(basename $PYFLE .py).pyc $PWD
rm $PWD/__pycache__/*$(basename $PYFILE .py)*
